version: 2.1
orbs:
  sonarqube: clicklogiq/sonarqube@1.0.1
jobs:
  code-analysis:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      - add_ssh_keys:
          fingerprints:
          - "fa:de:2a:6d:ab:5e:b1:23:26:cd:55:12:c4:d4:0d:b1"
      - checkout
      - run:
          name: code-coverage
          command: |
            cd /home/circleci/project/
            ls -lrt /home/circleci/project/
            mvn clean test sonar:sonar   -Dsonar.projectKey=petclinic   -Dsonar.host.url=http://ec2-3-110-118-101.ap-south-1.compute.amazonaws.com:9000   -Dsonar.login=sqp_f0dc3d706865eaf72e76fc0147b4d43a64dc011c
workflows:
  main-workflow:
    jobs:
      - code-analysis
